apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vote-app-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Ahmedhessn/VOTE-APP-V-3
    targetRevision: main
    path: vote-app-chart
    helm:
      valueFiles:
        - values.yaml
        - aks/values-production.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

