{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  labels:
    app: {{ include "vote-app.name" . }}
    chart: {{ include "vote-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.secret.user }}
  POSTGRES_PASSWORD: {{ .Values.postgres.secret.password }}
{{- end }}

